// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $index from "./routes/index.tsx";
import * as $posts_name_ from "./routes/posts/[name].tsx";
import * as $posts_index from "./routes/posts/index.tsx";
import * as $Dropdown from "./islands/Dropdown.tsx";
import * as $MultiSelect from "./islands/MultiSelect.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $PostIndexForm from "./islands/PostIndexForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/index.tsx": $index,
    "./routes/posts/[name].tsx": $posts_name_,
    "./routes/posts/index.tsx": $posts_index,
  },
  islands: {
    "./islands/Dropdown.tsx": $Dropdown,
    "./islands/MultiSelect.tsx": $MultiSelect,
    "./islands/Nav.tsx": $Nav,
    "./islands/PostIndexForm.tsx": $PostIndexForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
